spring.application.name=transportistas

# Configuración básica para desarrollo local
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Actualiza el esquema de la BD automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexion con Azure AD
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://taller2cloudnativrobvel.b2clogin.com/ec9b24df-ea23-4ac3-99b4-0afaa3cdcfb7/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://taller2cloudnativrobvel.b2clogin.com/taller2cloudnativrobvel.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_flujousuariotaller
logging.level.org.springframework.security=DEBUG