spring.application.name=transportistas

# ==========================================
# Configuración Base de Datos (Oracle XE Local)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# Configuración de JPA / Hibernate para Auto-creación
# ==========================================
# Fuerza el dialecto correcto para Oracle (evita que falle silenciosamente en XE)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Actualiza el esquema de la BD automáticamente al iniciar la aplicación
spring.jpa.hibernate.ddl-auto=update

# Muestra y formatea el SQL de inicialización en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ==========================================
# Conexión con Azure AD B2C
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://taller2cloudnativrobvel.b2clogin.com/ec9b24df-ea23-4ac3-99b4-0afaa3cdcfb7/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://taller2cloudnativrobvel.b2clogin.com/taller2cloudnativrobvel.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_flujousuariotaller
logging.level.org.springframework.security=DEBUG

# ==========================================
# Configuración RabbitMQ para pruebas en Localhost
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Activa la conexión segura SSL/TLS con el broker en producción si se requiere (false para pruebas locales)
spring.rabbitmq.ssl.enabled=false

# ==========================================
# Configuración de Spring Boot Actuator
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always